### ISSUE TITLE
type piracy in `convert` causes ambiguity errors

### ISSUE THREAD

**Issue by simeonschaub** [wildart/LMDB.jl#29]
This definition of `convert` is type piracy, since LMDB doesn't own the `Ref` type:

https://github.com/wildart/LMDB.jl/blob/6212c617976289f8ee0cbeca52a4f3c73114e0b6/src/common.jl#L12

Among the usual problems with type piracy, this also causes ambiguities for `convert(Any, ::Ref{MDB_val})`. Caught in the PkgEval run for https://github.com/JuliaLang/julia/pull/43671, see: https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/3656ddf_vs_1db8b8f/LMDB.primary.log

I'd recommend just removing this definition.

**Comment by meggart** [comment]
> This definition of convert is type piracy, since LMDB doesn't own the Ref type

Really? This is only called when a `Ref{MDBVal}` is involved so I don't really see how this should modify the behavior of existing programs. I will look into fixing this once your PR got merged, so it gets easier to test this.

**Comment by simeonschaub** [comment]
This is a bit of a grey area, but defining methods on functions you don't own on types you don't own, even if you own one of the type parameter can still lead to unexpected behavior.

The reproducer for this is quite easy, you just call `convert(Any, Ref{MDBVal}())`, which should fail on current julia releases as well.

**Comment by wildart** [comment]
I aggree with @simeonschaub. All these `_convert` methods should really be `convert` in that case it's clear what kind of conversion is lacking, if any.

**Comment by meggart** [comment]
In principle that would be fine. However, wouldn't then the ambiguity come from this method (if we rename it `convert`) https://github.com/wildart/LMDB.jl/blob/6212c617976289f8ee0cbeca52a4f3c73114e0b6/src/common.jl#L20 which still has an unbound first argument, so that `convert(Any, MDBVal)` would be ambigous? I personally would suggest two options to solving this:

1) Not extending `convert` at all but rather renaming the function to something like `mbd_unpack`, over which we have full control, This would be breaking, but ok IMO, since the package was just revived and should not have a large userbase in its current version.
2) Just fixing the ambiguity by defining `convert(::Type{Any}, v::Ref{MDBVal}) = v` 

Probably @simeonschaub will suggest to implement the first option, although my lazy self go rather go for 2)

**Comment by simeonschaub** [comment]
It's your package, so I won't tell you how it's supposed to work. You might be interested in the discussion in https://github.com/invenia/Intervals.jl/issues/144 regarding approach 2 though.

**Comment by meggart** [comment]
Ok, thanks for the link. I will check their proposed solution in more detail and will probably go for 1) then.
